services:
  vault:
    image: hashicorp/vault:1.16
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
    ports:
      - "8200:8200"
    command: server -dev
    healthcheck:
      test: ["CMD-SHELL", "vault status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d myapp"]
      interval: 5s
      timeout: 5s
      retries: 20

  bootstrap:
    image: postgres:18
    depends_on:
      postgres:
        condition: service_healthy
      vault:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./sql:/app/sql:ro
    environment:
      PGHOST: postgres
      PGUSER: admin
      PGPASSWORD: secret
      PGDATABASE: postgres
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
    entrypoint: ["/bin/bash"]
    command: "sql/init_db.sh"
