[project]
name = "fastapi-crm-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "alembic",
  "async-lru",
  "authlib",
  "click",
  "fastapi[standard]",
  "httpx",
  "hvac",
  "itsdangerous",
  "psycopg",
  "pydantic[email]",
  "pyjwt",
  "python-dotenv",
  "python-keycloak",
  "redis[hiredis]",
  "sqlalchemy",
]

[dependency-groups]
dev = [
  "faker",
  "pytest",
  "rich",
  "ruff",
  "ty",
]

[tool.fastapi]
entrypoint = "app.main:app"

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["app"]
