"""Add search client index

Revision ID: 15b6b6ad9128
Revises: d53fef6cf2be
Create Date: 2026-09-01 21:52:24.566567

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15b6b6ad9128"
down_revision: Union[str, Sequence[str], None] = "d53fef6cf2be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "search_name",
            sa.String(length=255),
            sa.Computed(
                "lower(trim(coalesce(trim(first_name), '') || ' ' || coalesce(trim(last_name), '')))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_clients_search_name_trgm",
        "clients",
        ["search_name"],
        postgresql_using="gin",
        postgresql_ops={"search_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_search_name_trgm"), table_name="clients")
    op.drop_column("clients", "search_name")
    # ### end Alembic commands ###
