"""Add user search index

Revision ID: 314c56e00f3a
Revises: 5b85600a72c4
Create Date: 2026-09-01 22:34:19.471596

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "314c56e00f3a"
down_revision: Union[str, Sequence[str], None] = "5b85600a72c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "search_name",
            sa.String(length=255),
            sa.Computed(
                "lower(trim(coalesce(trim(first_name), '') || ' ' || coalesce(trim(last_name), '')))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_users_search_name_trgm",
        "users",
        ["search_name"],
        postgresql_using="gin",
        postgresql_ops={"search_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_search_name_trgm"), table_name="users")
    op.drop_column("users", "search_name")
    # ### end Alembic commands ###
