"""Add owner_id column

Revision ID: 55407e935408
Revises: 587540bbc901
Create Date: 2026-07-20 22:26:37.032955

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55407e935408"
down_revision: Union[str, Sequence[str], None] = "587540bbc901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "clients", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "owner_id")
    # ### end Alembic commands ###
