"""Add search group index

Revision ID: 5b85600a72c4
Revises: 15b6b6ad9128
Create Date: 2026-09-01 21:55:25.121742

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b85600a72c4"
down_revision: Union[str, Sequence[str], None] = "15b6b6ad9128"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    # ### end Alembic commands ###
