"""Add client RLS policy

Revision ID: c58cd4efe58f
Revises: 55407e935408
Create Date: 2026-07-21 21:38:01.230393

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c58cd4efe58f"
down_revision: Union[str, Sequence[str], None] = "55407e935408"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
    """)

    op.execute("""
        CREATE POLICY clients_owner_policy
        ON clients
        FOR ALL
        USING (
            COALESCE(current_setting('app.enable_rls', true)::boolean, true) = false
            OR owner_id = current_setting('app.current_user_id', true)::int
        )
        WITH CHECK (
            COALESCE(current_setting('app.enable_rls', true)::boolean, true) = false
            OR owner_id = current_setting('app.current_user_id', true)::int
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DROP POLICY IF EXISTS clients_owner_policy ON clients;
    """)
    op.execute("""
        ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
    """)
    # ### end Alembic commands ###
