"""Add admin user

Revision ID: d53fef6cf2be
Revises: 493102bd87ba
Create Date: 2026-08-29 13:49:15.542699

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.utils.keycloak import create_user, delete_user

# revision identifiers, used by Alembic.
revision: str = "d53fef6cf2be"
down_revision: Union[str, Sequence[str], None] = "493102bd87ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    # Add admin user
    keycloak_id = create_user("admin", "admin@example.com", "Admin", "User")
    op.execute(
        sa.text("""
            INSERT INTO users (email, username, keycloak_id, first_name, last_name)
            VALUES (:email, :username, :keycloak_id, :first_name, :last_name)
            ON CONFLICT (username) DO NOTHING
        """).bindparams(
            sa.bindparam("email", value="admin@example.com"),
            sa.bindparam("username", value="admin"),
            sa.bindparam("keycloak_id", value=keycloak_id),
            sa.bindparam("first_name", value="Admin"),
            sa.bindparam("last_name", value="User"),
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    delete_user("admin")
